/**
 * Alert notification service.
 * Phase 18: Sends email notifications for alerts via Resend.
 */
import { Resend } from "resend";
import { createLogger } from "@/server/lib/logger";
import type { AlertSelect, AlertRuleSelect } from "@/db/alert-schema";
import { updateAlertEmailStatus } from "./alerts";

const log = createLogger({ module: "alert-notifications" });

const DEFAULT_FROM = "alerts@tevero.io";

/**
 * Check if email should be sent for this alert.
 */
export function shouldSendEmail(alert: AlertSelect, rule: AlertRuleSelect | null): boolean {
  // No email if rule doesn't exist or email disabled
  if (!rule || !rule.emailNotify) {
    return false;
  }

  // Only send for warning and critical severity
  if (alert.severity === "info") {
    return false;
  }

  // Don't re-send if already sent
  if (alert.emailSentAt) {
    return false;
  }

  return true;
}

/**
 * Generate email subject for an alert.
 */
function getEmailSubject(alert: AlertSelect): string {
  const severityPrefix = alert.severity === "critical" ? "🚨 CRITICAL: " : "⚠️ ";
  return `${severityPrefix}${alert.title}`;
}

/**
 * Generate email HTML template for an alert.
 */
export function getAlertEmailTemplate(alert: AlertSelect, dashboardUrl: string): string {
  const severityColors = {
    info: "#3b82f6",
    warning: "#f59e0b",
    critical: "#ef4444",
  };

  const severityColor = severityColors[alert.severity as keyof typeof severityColors] ?? "#6b7280";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1f2937; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, ${severityColor}22 0%, ${severityColor}11 100%); border-left: 4px solid ${severityColor}; padding: 20px; border-radius: 4px; margin-bottom: 24px;">
    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 12px;">
      <span style="background: ${severityColor}; color: white; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; text-transform: uppercase;">
        ${alert.severity}
      </span>
      <span style="color: #6b7280; font-size: 14px;">
        ${alert.alertType.replace(/_/g, " ")}
      </span>
    </div>
    <h1 style="margin: 0 0 12px 0; font-size: 20px; font-weight: 600; color: #111827;">
      ${alert.title}
    </h1>
    <p style="margin: 0; color: #4b5563; font-size: 16px;">
      ${alert.message}
    </p>
  </div>

  <div style="margin-bottom: 24px;">
    <a href="${dashboardUrl}" style="display: inline-block; background: #2563eb; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: 500;">
      View in Dashboard
    </a>
  </div>

  <div style="border-top: 1px solid #e5e7eb; padding-top: 16px; color: #6b7280; font-size: 12px;">
    <p style="margin: 0;">
      This alert was generated by Tevero SEO Platform.
      <br>
      You can configure alert settings in your dashboard.
    </p>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Send alert email notification.
 */
export async function sendAlertEmail(
  alert: AlertSelect,
  recipientEmail: string,
  dashboardUrl: string,
): Promise<{ success: boolean; error?: string }> {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    log.warn("RESEND_API_KEY not configured, skipping alert email");
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  const resend = new Resend(apiKey);
  const fromAddress = process.env.ALERT_EMAIL_FROM ?? DEFAULT_FROM;

  const html = getAlertEmailTemplate(alert, dashboardUrl);
  const subject = getEmailSubject(alert);

  try {
    const { error } = await resend.emails.send({
      from: fromAddress,
      to: [recipientEmail],
      subject,
      html,
    });

    if (error) {
      log.error("Alert email send failed", new Error(error.message), {
        alertId: alert.id,
        to: recipientEmail,
      });
      await updateAlertEmailStatus(alert.id, null, error.message);
      return { success: false, error: error.message };
    }

    log.info("Alert email sent", {
      alertId: alert.id,
      to: recipientEmail,
      severity: alert.severity,
    });

    await updateAlertEmailStatus(alert.id, new Date(), null);
    return { success: true };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    log.error("Alert email exception", err instanceof Error ? err : new Error(errorMessage), {
      alertId: alert.id,
      to: recipientEmail,
    });
    await updateAlertEmailStatus(alert.id, null, errorMessage);
    return { success: false, error: errorMessage };
  }
}
